name: sleep_sync_app
description: "App de control de sueño para parejas."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sleep_ui_kit:
    path: ../sleep_ui_kit

  cupertino_icons: ^1.0.6

  # --- BACKEND & AUTH ---
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.2.1

  # --- GESTIÓN DE ESTADO ---
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # --- UI, GRÁFICOS & FUENTES ---
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1 # Para loaders elegantes

  # --- FECHAS & UTILIDADES ---
  intl: ^0.19.0
  jiffy: ^6.3.1 # Manejo simplificado de fechas y rangos
  uuid: ^4.4.0 # Generación de IDs para registros y códigos de pareja

  # --- NOTIFICACIONES LOCALES ---
  flutter_local_notifications: ^17.0.0
  share_plus: ^12.0.1
  rxdart: ^0.28.0

  shared_preferences: ^2.3.5
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  # Generadores de código para Riverpod
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - "assets/images/icon.png"
    - assets/animations/loading.json
    - assets/animations/bad.json
    - assets/animations/regular.json
    - assets/animations/good.json
    - assets/animations/searching.json
    - assets/sounds/send.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#0F172A"
  image: assets/images/icon.png

  android_12:
    image: assets/images/icon.png
    icon_background_color: "#0F172A"

  ios: true
  fullscreen: true
